//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSignMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        public int SignID { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public string FancyText { get; set; }
    }
}
